name: Release

on:
  push:
    tags:
      - '*-v*.*.*'

jobs:
  # TODO: Add jobs for `cargo test`, `cargo check`, and `cargo clippy`. All must pass before `release` can be run.
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo 'Hello World!'
      - run: |
          PACKAGE=$(echo '${{ github.ref_name }}' | sed 's/-v[0-9]\+\.[0-9]\+\.[0-9]\+.*$//')
          echo "package=$PACKAGE" | tee -a $GITHUB_OUTPUT $GITHUB_ENV

    # TODO: Create Github release based on above version/tag
